name: CI

on:
  workflow_dispatch:
  release:
  push:
  pull_request:
    branches: [master]

jobs:
  ci:
    strategy:
      matrix:
        os: [windows-2019]
        arch: [x86_64]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{matrix.arch}})
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: ^14.17.5
          scope: '@octocat'

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      
      - name: Install node-gyp
        run: npm install -g node-gyp@latest 

      - name: Install Packages
        run: npm i --ignore-scripts

      # Build and publish
      - name: Build & Publish Prebuilds
        run: npm run build:ci -- --msvs_version=2019
        env:
          ARCH: ${{ matrix.arch }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish NPM Package
        if: startsWith(github.ref, 'refs/tags/v') && startsWith(matrix.os, 'ubuntu')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
